export 'package:widgets_app/presentation/screen/animated/animated_screen.dart';
export 'package:widgets_app/presentation/screen/app_tutorial/app_tutorial_screen.dart';
export 'package:widgets_app/presentation/screen/buttons/buttons_screen.dart';
export 'package:widgets_app/presentation/screen/cards/cards_screen.dart';
export 'package:widgets_app/presentation/screen/home/home_screen.dart';
export 'package:widgets_app/presentation/screen/infinite_scroll/infinite_scroll_screen.dart';
export 'package:widgets_app/presentation/screen/progress/progress_screen.dart';
export 'package:widgets_app/presentation/screen/snackbar/snackbar_screen.dart';
export 'package:widgets_app/presentation/screen/ui_controls/ui_controls_screen.dart';
